apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1m
      receiver: 'default'
      routes:
      - match:
          alertname: 'scaleup'
        receiver: 'webhook.scaleup'
      - match:
          alertname: 'scaledown'
        receiver: 'webhook.scaledown'
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']
    receivers:
    - name: default
    - name: 'webhook.scaleup'
      webhook_configs:
      - url: 'http://webhook:9000/hooks/scaleup'
    - name: 'webhook.scaledown'
      webhook_configs:
      - url: 'http://webhook:9000/hooks/scaledown'
type: Opaque
