apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - "name": "logging-webhook"
      "webhook_configs":
      - "url": "http://webhook.webhook.svc.cluster.local:8080/log"
    - "name": "wls-scaleup"
      "webhook_configs":
      - "url": "http://webhook:9000/hooks/scaleup"
    "route":
      "group_by":
      - "namespace"
      - "alertname"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "wls-scaleup"
      "repeat_interval": "1h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "Watchdog"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
      - "match":
          "alertname": "ClusterWarning"
        "receiver": "logging-webhook"
      - "match":
          "alertname": "ClusterWarning"
        "receiver": "wls-scaleup"
type: Opaque
