apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.25.0
    prometheus: k8s
    role: alert-rules
  name: wls-sample-domain1-prometheus-rules
  namespace: monitoring
spec:
  groups:
  - name: wls-sample-domain1
    rules:
    - record: webapp:webapp_config_open_sessions_current_count:avg
      expr: avg(webapp_config_open_sessions_current_count{webapp="myapp2"})
    - alert: scaleup
      for: 5m
      expr: webapp:webapp_config_open_sessions_current_count:avg > 10
      annotations:
        description: 'Scale up when current sessions is greater than 15.'
        summary: 'Firing when total sessions active greater than 15.'
    - alert: scaledown
      for: 5m
      expr: webapp:webapp_config_open_sessions_current_count:avg < 4
      annotations:
        description: 'Scale down when current sessions is less than 4.'
        summary: 'Firing when total sessions active less than 4'